# Generated by Django 4.1.6 on 2023-02-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_photo_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('pk',), 'verbose_name': 'foto', 'verbose_name_plural': 'fotos'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'verbose_name': 'postagem', 'verbose_name_plural': 'postagens'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titulo'),
        ),
    ]
